management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/retail?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: root
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
